server:
  port: 5001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: asianwallets-base5001
    prefer-ip-address: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.124.34:3306/asianwallets_saas?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
            dataSource: quartzDs
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: JDBC
    #初始化表结构
    jdbc:
      initialize-schema: NEVER
  # rabbitMq 配置
  rabbitmq:
    addresses: 192.168.124.34:5672
    username: admin
    password: admin

redis:
  database: 1
  password: test123
  host: 192.168.124.34
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1
custom:
  #AD3给亚洲钱包提供的商户号
  merchantCode: 20170921500144
  #help2Pay给亚洲钱包提供的商户号
  help2PayMerchantCode: 898763663360
  warning:
    email: 842505302@qq.com
    mobile: 18800330943
  alipay:
    url: https://intlmapi.alipay.com/gateway.do?

#项目自定义配置
file:
  http:
    server: http://192.168.124.27:8080
    basServer: http://192.168.124.27:5001/qr/forward?id=
    frontPage: https://www.baidu.com
  upload:
    path: C:\apache-tomcat-8.5.38\webapps
  tmpfile: C:\apache-tomcat-8.5.38\webapps\tmp