server:
  port: 5004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: asianwallets-message5004
    prefer-ip-address: true

#项目自定义配置
custom:
###国际短信配置
sms:
  send:
    api:
      inter:
        account: I3041456
        pwd: 1f5SgI6rK77d4e
        intapi: http://intapi.253.com/send/json

      ###普通短信配置
      simple:
        account: N6611753
        pwd: R4VljTqHwr51ec
        batchSendSM: http://smssh1.253.com/msg/HttpBatchSendSM

###邮箱配置
msg:
  send:
    api:
      simple:
        account: vnbig_noreply
        key: N7IvBFVcNBjx4gUS
        name: www
        url: http://api.sendcloud.net/apiv2/mail/send
      emailFrom: jack@www.com
