server:
  port: 5004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: asianwallets-message5004
    prefer-ip-address: true

#项目自定义配置
custom:

###国际短信配置
sms:
  send:
    api:
      inter:
        account: I5404708
        pwd: 6Sos0QFKRP0e3c
        intapi: http://intapi.253.com/send/json

      ###普通短信配置
      simple:
        account: N5845811
        pwd: FaqX6U3WPBe208
        batchSendSM: http://zapi.253.com/msg/HttpBatchSendSM

###邮箱配置
msg:
  send:
    api:
      simple:
        account: asianwallets_test_o4fkUZ
        key: FpCvIVQtQsRSd32A
        name: asianwallets
        url: http://api.sendcloud.net/apiv2/mail/send
      emailFrom: info@asianwallets.com