package com.asianwallets.trade.dto;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

@Data
@ApiModel(value = "Doku线上网银服务器回调实体", description = "Doku线上网银服务器回调实体")
public class DokuServerCallbackDTO {

    @ApiModelProperty(value = "订单金额")
    private String AMOUNT;

    @ApiModelProperty(value = "订单号")
    private String TRANSIDMERCHANT;

    @ApiModelProperty(value = "签名")
    private String WORDS;

    @ApiModelProperty(value = "Default value : P")
    private String STATUSTYPE;

    @ApiModelProperty(value = "0000: Success, others Failed")
    private String RESPONSECODE;

    @ApiModelProperty(value = "Transaction number from bank")
    private String APPROVALCODE;

    @ApiModelProperty(value = "SUCCESS / FAILED")
    private String RESULTMSG;

    @ApiModelProperty(value = "See payment channel code lis")
    private String PAYMENTCHANNEL;

    @ApiModelProperty(value = "Virtual Account identifier for VA transaction. Has value if using Channel that has payment code")
    private String PAYMENTCODE;

    @ApiModelProperty(value = "DOKU will return the value from Payment Request.")
    private String SESSIONID;

    @ApiModelProperty(value = "Bank Issuer")
    private String BANK;

    @ApiModelProperty(value = "YYYYMMDDHHMMSS")
    private String PAYMENTDATETIME;

    @ApiModelProperty(value = "Generated by Fraud Screening (RequestID)")
    private String VERIFYID;

    @ApiModelProperty(value = "0 - 100")
    private String VERIFYSCORE;

    @ApiModelProperty(value = "APPROVE / REJECT / REVIEW / HIGHRISK / NA")
    private String VERIFYSTATUS;

    @ApiModelProperty(value = "ISO3166 , numeric code")
    private String CURRENCY;

    @ApiModelProperty(value = "ISO3166 , numeric code")
    private String PURCHASECURRENCY;

    @ApiModelProperty(value = "VISA / MASTERCARD")
    private String BRAND;

    @ApiModelProperty(value = "Cardholder Name")
    private String CHNAME;

    @ApiModelProperty(value = "TRUE / FALSE")
    private String THREEDSECURESTATUS;

    @ApiModelProperty(value = "CUSTOMER / MERCHANT / NA")
    private String LIABILITY;

    @ApiModelProperty(value = "Always be : NA")
    private String EDUSTATUS;

    @ApiModelProperty(value = "Merchant’s customer identifier (If using Tokenization)")
    private String CUSTOMERID;

    @ApiModelProperty(value = "Tokenized Card’s Identifier (If using Tokenization)")
    private String TOKENID;

}
