server:
  port: 5005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: asianwallets-channels5005
    prefer-ip-address: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.124.34:3306/asianwallets_saas?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# redis 配置
redis:
  database: 1
  password: test123
  host: 192.168.124.34
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1

#项目自定义配置
custom:
  ad3:
    onlineBank: http://202.79.207.135:8000/CBPayGW/v1/beforSendToItsPay
    onlineQuery: http://202.79.207.135:8000/CBPayGW/v1/merQueryOneOrder.json
    onlineRefund: http://202.79.207.135:8000/CBPayGW/v1/beforSendToItsRefund.json

    offlineScan: http://202.79.207.135:8000/CBPayGW/posPay.json
    offlineQuery: http://202.79.207.135:8000/CBPayGW/terminalQueryOrder.json
    offlineRefund: http://202.79.207.135:8000/CBPayGW/posRefund.json
  local:
    eNets-jumpurl: https://pag.asianwallets.com/cha/enets/sendToeNetsDebitPay/
  eghl:
    pay-url: https://securepay.e-ghl.com/IPG/Payment.aspx
  megaPay:
    megaPayTHBUrl: https://www.megapay.in.th/payment/megapayinv.aspx
    megaPayIDRUrl: https://www.nextpayremit.com/payinvi.aspx
    nextPosUrl: https://www.nextpos.asia/thaiqrstring/qrstring.aspx
    nextPosQueryUrl: https://www.nextpos.asia/thaiqr/queryorder.aspx
    nextPosRefundUrl: https://www.nextpos.asia/thaiqr/refund.aspx
  vtcPay:
    vtcPayUrl: https://vtcpay.vn/bank-gateway/checkout.html
  eNets:
    eNetsDebit: https://www2.enets.sg/
    eNetsSM: https://api.nets.com.sg/GW2/TxnReqListener
    eNetsPOS: https://uat-api.nets.com.sg:9065/uat/merchantservices/qr/dynamic/v1/order/request
  #    eNetsPOS: https://api.nets.com.sg/merchantservices/qr/dynamic/v1/order/request
  help2Pay:
    help2PayUrl: http://api.besthappylife.biz/MerchantTransfer
    help2PayOutUrl: http://app.besthappylife.biz/MerchantPayout/M0285
    help2PayOutIP: 47.100.197.214
  aliPay:
    offlineBSC: https://intlmapi.alipay.com/gateway.do?
    CSB: https://intlmapi.alipay.com/gateway.do?
    refundUrl: https://intlmapi.alipay.com/gateway.do?
    onlineUrl: https://intlmapi.alipay.com/gateway.do?
  NganLuong:
    #    payUrl: https://sandbox.nganluong.vn:8088/nl35/checkout.api.nganluong.post.php
    payUrl: https://www.nganluong.vn/checkout.api.nganluong.post.php
  xendit:
    cusPayurl: https://api.xendit.co/v2/invoices
    payUrl: https://api.xendit.co/disbursements
    banksUrl: https://api.xendit.co/available_disbursements_banks
  wechat:
    offlineCSB: https://api.mch.weixin.qq.com/pay/unifiedorder
    offlineBSC: https://api.mch.weixin.qq.com/pay/micropay
    queryUrl: https://api.mch.weixin.qq.com/pay/orderquery
    wechatRefundUrl: https://api.mch.weixin.qq.com/secapi/pay/refund
    fliePath: /usr/CBPayFiles/ITS/channelcert/
    cancelUrl: https://api.mch.weixin.qq.com/secapi/pay/reverse
  doku:
    dokuPayUrl: https://staging.doku.com/Suite/Receive
    checkUrl: https://staging.doku.com/CheckStatus
    refundUrl: https://staging.doku.com/Suite/DoRefundRequest
  qfpay:
    csbUrl: http://testapi.qfpay.info/8081/api/v3/receiptsQRCode
    bscUrl: http://testapi.qfpay.info/8081/api/v3/scanQRCode
    queryUrl: http://testapi.qfpay.info/8081/api/v3/receiptsResult
    refundUrl: http://testapi.qfpay.info/8081/api/v3/refund
    refundSearchUrl: http://testapi.qfpay.info/8081/api/v3/refundHistory
  th:
    ip: 58.248.241.169
    port: 10089
    tdpu: 6006090000
    header: 800100000000
  upi:
    payUrl: https://testpay.sicpay.com/backSecure.do
    privateKeyPath: /testKey/549440189990001.pem
    publicKeyPath: /testKey/GHT_ROOT.pem
