server:
  port: 5010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: asianwallets-trade5010
    prefer-ip-address: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.124.34:3306/asianwallets_saas?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # rabbitMq 配置
  rabbitmq:
    addresses: 192.168.124.34:5672
    username: admin
    password: admin

# redis 配置
redis:
  database: 1
  password: test123
  host: 192.168.124.34
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1

#项目自定义配置
custom:
  warning:
    email: 842505302@qq.com
    mobile: 18800330943
  jwt:
    secret: piHRSk3tgcMNZtZl
    token_expire_hour: 24

  #nextPos分发AD3地址
  nextPosUrl: http://119.23.136.80/ITSBoss/nextPosNotifyAction/nextPosqrbackNotify.do

  #megaPay分发AD3地址
  ad3ItsUrl: http://119.23.136.80/ITSBoss/v1/

  #收银台url
  cashierDeskUrl: http://192.168.124.32:8087/checkstandweb/#/main

  #亚洲钱包的支付页面的url
  paySuccessUrl: http://192.168.124.32:8087/checkstandweb/#/Success

  #AD3提供的测试参数
  #url
  ad3Url: http://119.23.136.71/CBPayGW
  #AD3给亚洲钱包提供的商户号---线上商户号
  merchantCode: 20190524500137
  imei: 2222222
  operatorId: '00'  #操作员ID，字符串
  password: a123456
  tradePwd: a123456
  #AD3给亚洲钱包提供的商户号---线下商户号
  merchantCodeOffline: 20200115500444
  imeiOffline: 3333333
  operatorIdOffline: '00'  #操作员ID，字符串
  passwordOffline: a123456
  tradePwdOffline: a123456

  #线上 指定密钥的提供方 1为使用平台提供的密钥 2为使用自己生成的密钥
  merchantSignType: 2
  #线上 私钥 与提供方有关
  platformProvidesPrivateKey: >
    MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANOOmUzJA
    /AfBF3W1o/8PT0mrJkwIPdU0YaqAvhwCGzzPZWWyt/i4RfAIm3qdEQV7j
    jPpO5oq9ZKa2zh34rwan+CdP9eNATo6obOzxZS9BcWuYhbAwtYWa9F+lc
    frlfXgwdhD+YjWY4bfNYAJVXgtg3fmcoqsiD0Z3vEw88p0Y8DAgMBAAEC
    gYAW01jo9vtMyhvvgAGQcXeuBGE0+gNkjCs7K1a8tWHDV486d5WWCGWe6
    WUNlPFMc01LpeO2sWZw7YCfs9Mpq3zh6Nid7cCOQkl8IJP5CxXsG1U5Ub
    7x07+8o6pf0uFWc1DJvWML6vDEOTFQLjrvCDVskE4uh9NIqZMaoV+GdEi
    3AQJBAOy7KzjZte3GSQ+Qx//R0TYYAWmTkPucK55DHnfnNz837I43ejwd
    w+4BS2szDj7WgcuQHf4zLibXwoUPYCW6FIECQQDkxt7QEwWjEOSlbRhzZ
    KDZc1fXr0kG6ndCPBv48Ry7zRNufruNkTCHSSryYqXwa3wV90Aj4tF2yd
    LvwqHH/JGDAkEA5mU3KKpCdLqhiqOm8qQa0GHGpiD3XtncXbgHJD0EuON
    NuA/oSC/T64SZCSj0eVW9lweZGThod2dPqr6PHcifgQJAY4iGbh6oiC6U
    W8igJ6wzMwg0wpj3e7PM2RtPzDoSlz584sjujoQJigJyVexHZ9dLsD7XQ
    AWxvi3GwRt7yYeAQwJAI9JhK5ZlbKiOOwsjcJQEQADefTRoBrrxL1xzWL
    0bPWL4jfacmREho/etFeVSu5rKFk5WQpsuLPv9B7vL7Towqg==

  #NL查询URL
  nganLuong:
    check_url: https://www.nganluong.vn/checkout.api.nganluong.post.php
  #给AD3的回调URL
  channelCallbackUrl: http://127.0.0.1:9004

