server:
  port: 5010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: asianwallets-trade5010
    prefer-ip-address: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://db.asia:3306/asianwallets_saas?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: asianwallets
    password: QJI1Zh((FSFAyAAf
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # rabbitMq 配置
  rabbitmq:
    addresses: mq01.asia:5672
    username: admin
    password: C4wtEiB8GPkSXqfi

# redis 配置
redis:
  database: 0
  password: Uj7cELl8emRBqPEE
  host: redis.asia
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1

#项目自定义配置
custom:
  warning:
    email: 842505302@qq.com
    mobile: 18800330943
  jwt:
    secret: M2UwFPOfdPW2JqI5
    token_expire_hour: 24

  #nextPos分发AD3地址
  nextPosUrl: https://its.alldebitpay.com/nextPosNotifyAction/nextPosqrbackNotify.do

  #megaPayAD3分发地址
  ad3ItsUrl: https://its.alldebitpay.com/v1/

  #收银台url
  cashierDeskUrl: https://testsaas.asianwallets.com/checkstandweb/#/main

  #亚洲钱包的支付页面的url
  paySuccessUrl: https://testsaas.asianwallets.com/checkstandweb/#/Success
  #AD3提供的生产环境地址
  #url
  ad3Url: https://pgw.alldebitpay.com

  #线上 指定密钥的提供方 1为使用平台提供的密钥 2为使用自己生成的密钥
  merchantSignType: 2

  #NL查询URL
  nganLuong:
    check_url: https://www.nganluong.vn/checkout.api.nganluong.post.php
  #给AD3的回调URL
  channelCallbackUrl: https://testsaas.asianwallets.com/tra
  upi:
    privateKeyPath: /testKey/00001936.pem
    publicKeyPath: /testKey/GHT_ROOT_PROD.pem
    tdpu: 6000060000
    header: 601410190121
