server:
  port: 5010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instance-id: asianwallets-trade5010
    prefer-ip-address: true

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 600000
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.124.34:3306/asianwallets_saas?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # rabbitMq 配置
  rabbitmq:
    addresses: 192.168.124.34:5672
    username: admin
    password: admin

# redis 配置
redis:
  database: 1
  password: test123
  host: 192.168.124.34
  port: 6379
  time: 0
  pool:
    max-idle: 100
    min-idle: 5
    max-total: 100
    max-wait-millis: -1

#项目自定义配置
custom:
  warning:
    email: 842505302@qq.com
    mobile: 18800330943
  jwt:
    secret: piHRSk3tgcMNZtZl
    token_expire_hour: 24

  #nextPos分发AD3地址
  nextPosUrl: http://119.23.136.80/ITSBoss/nextPosNotifyAction/nextPosqrbackNotify.do

  #megaPay分发AD3地址
  ad3ItsUrl: http://119.23.136.80/ITSBoss/v1/

  #收银台url
  cashierDeskUrl: http://192.168.124.32:8087/saascheckstandweb/#/main

  #亚洲钱包的支付页面的url
  paySuccessUrl: http://192.168.124.32:8087/saascheckstandweb/#/Success

  #AD3提供的测试参数
  #url
  ad3Url: http://119.23.136.71/CBPayGW

  #线上 指定密钥的提供方 1为使用平台提供的密钥 2为使用自己生成的密钥
  merchantSignType: 2

  #NL查询URL
  nganLuong:
    check_url: https://www.nganluong.vn/checkout.api.nganluong.post.php
  #给AD3的回调URL
  channelCallbackUrl: http://127.0.0.1:9004
  upi:
    privateKeyPath: /testKey/549440189990001.pem
    publicKeyPath: /testKey/GHT_ROOT.pem
    tdpu: 6000060000
    header: 601410190121
